Set Theme catppuccin-latte
Set WindowBar Colorful
Set Margin 10
Set BorderRadius 10
Set Shell fish
Set FontFamily "Hack"
Set FontSize 16
Set MarginFill "#D3DBD8"
Set Padding 4
Set Width 800
Set Height 600
Output output/startpoint-catppuccin-latte.gif
Sleep 0s
Hide
Type "startpoint -w ~/demo/"
Escape
Sleep 500ms
Enter
Show
Sleep 1s
Screenshot output/startpoint-catppuccin-latte.png
Down
Sleep 0.2s
Down
Sleep 1.5s
Type "p"
Sleep 3s
Escape
Sleep 1s
Type "r"
Sleep 10s
